import { defineConfig } from "tsup";

export default defineConfig([
  {
    dts: false,
    shims: true,
    clean: true,
    bundle: true,
    silent: true,
    sourcemap: false,
    splitting: false,
    treeshake: false,
    cjsInterop: true,
    name: 'bin',
    outDir: 'bin',
    minify: 'terser',
    platform: 'node',
    format: ['cjs'],
    entry: { bedo: 'src/bin.ts', bedox: 'src/binx.ts' },
  },
  {
    dts: false,
    shims: true,
    clean: true,
    bundle: true,
    silent: true,
    sourcemap: true,
    splitting: false,
    treeshake: true,
    cjsInterop: true,
    name: 'lib',
    outDir: 'lib',
    minify: 'terser',
    platform: 'node',
    format: ['cjs', 'esm'],
    entry: ['src/loop.ts', 'src/setup.ts', 'src/mod.ts'],
  },
  {
    dts: true,
    shims: true,
    clean: false,
    bundle: true,
    silent: true,
    sourcemap: true,
    splitting: false,
    treeshake: true,
    cjsInterop: true,
    name: 'lib/types',
    outDir: 'lib',
    minify: 'terser',
    platform: 'node',
    format: ['esm'],
    entry: ['src/loop.ts', 'src/setup.ts', 'src/mod.ts'],
  },
])
